// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpCommFtp;
import javax.persistence.Entity;
import javax.persistence.Table;

privileged aspect DdpCommFtp_Roo_Jpa_Entity {
    
    declare @type: DdpCommFtp: @Entity;
    
    declare @type: DdpCommFtp: @Table(schema = "dbo", name = "DDP_COMM_FTP");
    
}
