// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpExportSuccessReport;
import com.agility.ddp.data.domain.DdpExportSuccessReportRepository;
import com.agility.ddp.data.domain.DdpExportSuccessReportServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DdpExportSuccessReportServiceImpl_Roo_Service {
    
    declare @type: DdpExportSuccessReportServiceImpl: @Service;
    
    declare @type: DdpExportSuccessReportServiceImpl: @Transactional;
    
    @Autowired
    DdpExportSuccessReportRepository DdpExportSuccessReportServiceImpl.ddpExportSuccessReportRepository;
    
    public long DdpExportSuccessReportServiceImpl.countAllDdpExportSuccessReports() {
        return ddpExportSuccessReportRepository.count();
    }
    
    public void DdpExportSuccessReportServiceImpl.deleteDdpExportSuccessReport(DdpExportSuccessReport ddpExportSuccessReport) {
        ddpExportSuccessReportRepository.delete(ddpExportSuccessReport);
    }
    
    public DdpExportSuccessReport DdpExportSuccessReportServiceImpl.findDdpExportSuccessReport(Integer id) {
        return ddpExportSuccessReportRepository.findOne(id);
    }
    
    public List<DdpExportSuccessReport> DdpExportSuccessReportServiceImpl.findAllDdpExportSuccessReports() {
        return ddpExportSuccessReportRepository.findAll();
    }
    
    public List<DdpExportSuccessReport> DdpExportSuccessReportServiceImpl.findDdpExportSuccessReportEntries(int firstResult, int maxResults) {
        return ddpExportSuccessReportRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void DdpExportSuccessReportServiceImpl.saveDdpExportSuccessReport(DdpExportSuccessReport ddpExportSuccessReport) {
        ddpExportSuccessReportRepository.save(ddpExportSuccessReport);
    }
    
    public DdpExportSuccessReport DdpExportSuccessReportServiceImpl.updateDdpExportSuccessReport(DdpExportSuccessReport ddpExportSuccessReport) {
        return ddpExportSuccessReportRepository.save(ddpExportSuccessReport);
    }
    
}
