// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpGenSourceLkpPK;
import java.io.Serializable;

privileged aspect DdpGenSourceLkpPK_Roo_Serializable {
    
    declare parents: DdpGenSourceLkpPK implements Serializable;
    
    private static final long DdpGenSourceLkpPK.serialVersionUID = 1L;
    
}
