// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpCommEmailDataOnDemand;
import com.agility.ddp.data.domain.DdpCommEmailIntegrationTest;
import com.agility.ddp.data.domain.DdpCommEmailRepository;
import com.agility.ddp.data.domain.DdpCommEmailService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DdpCommEmailIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DdpCommEmailIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DdpCommEmailIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DdpCommEmailIntegrationTest: @Transactional;
    
    @Autowired
    DdpCommEmailDataOnDemand DdpCommEmailIntegrationTest.dod;
    
    @Autowired
    DdpCommEmailService DdpCommEmailIntegrationTest.ddpCommEmailService;
    
    @Autowired
    DdpCommEmailRepository DdpCommEmailIntegrationTest.ddpCommEmailRepository;
    
    @Test
    public void DdpCommEmailIntegrationTest.testCountAllDdpCommEmails() {
        Assert.assertNotNull("Data on demand for 'DdpCommEmail' failed to initialize correctly", dod.getRandomDdpCommEmail());
        long count = ddpCommEmailService.countAllDdpCommEmails();
        Assert.assertTrue("Counter for 'DdpCommEmail' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DdpCommEmailIntegrationTest.testFindDdpCommEmail() {
        DdpCommEmail obj = dod.getRandomDdpCommEmail();
        Assert.assertNotNull("Data on demand for 'DdpCommEmail' failed to initialize correctly", obj);
        Integer id = obj.getCemEmailId();
        Assert.assertNotNull("Data on demand for 'DdpCommEmail' failed to provide an identifier", id);
        obj = ddpCommEmailService.findDdpCommEmail(id);
        Assert.assertNotNull("Find method for 'DdpCommEmail' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DdpCommEmail' returned the incorrect identifier", id, obj.getCemEmailId());
    }
    
    @Test
    public void DdpCommEmailIntegrationTest.testFindAllDdpCommEmails() {
        Assert.assertNotNull("Data on demand for 'DdpCommEmail' failed to initialize correctly", dod.getRandomDdpCommEmail());
        long count = ddpCommEmailService.countAllDdpCommEmails();
        Assert.assertTrue("Too expensive to perform a find all test for 'DdpCommEmail', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DdpCommEmail> result = ddpCommEmailService.findAllDdpCommEmails();
        Assert.assertNotNull("Find all method for 'DdpCommEmail' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DdpCommEmail' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DdpCommEmailIntegrationTest.testFindDdpCommEmailEntries() {
        Assert.assertNotNull("Data on demand for 'DdpCommEmail' failed to initialize correctly", dod.getRandomDdpCommEmail());
        long count = ddpCommEmailService.countAllDdpCommEmails();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DdpCommEmail> result = ddpCommEmailService.findDdpCommEmailEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DdpCommEmail' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DdpCommEmail' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DdpCommEmailIntegrationTest.testSaveDdpCommEmail() {
        Assert.assertNotNull("Data on demand for 'DdpCommEmail' failed to initialize correctly", dod.getRandomDdpCommEmail());
        DdpCommEmail obj = dod.getNewTransientDdpCommEmail(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DdpCommEmail' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DdpCommEmail' identifier to be null", obj.getCemEmailId());
        try {
            ddpCommEmailService.saveDdpCommEmail(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        ddpCommEmailRepository.flush();
        Assert.assertNotNull("Expected 'DdpCommEmail' identifier to no longer be null", obj.getCemEmailId());
    }
    
    @Test
    public void DdpCommEmailIntegrationTest.testDeleteDdpCommEmail() {
        DdpCommEmail obj = dod.getRandomDdpCommEmail();
        Assert.assertNotNull("Data on demand for 'DdpCommEmail' failed to initialize correctly", obj);
        Integer id = obj.getCemEmailId();
        Assert.assertNotNull("Data on demand for 'DdpCommEmail' failed to provide an identifier", id);
        obj = ddpCommEmailService.findDdpCommEmail(id);
        ddpCommEmailService.deleteDdpCommEmail(obj);
        ddpCommEmailRepository.flush();
        Assert.assertNull("Failed to remove 'DdpCommEmail' with identifier '" + id + "'", ddpCommEmailService.findDdpCommEmail(id));
    }
    
}
