// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpCommunicationLkpDataOnDemand;
import com.agility.ddp.data.domain.DdpCommunicationLkpIntegrationTest;
import com.agility.ddp.data.domain.DdpCommunicationLkpRepository;
import com.agility.ddp.data.domain.DdpCommunicationLkpService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DdpCommunicationLkpIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DdpCommunicationLkpIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DdpCommunicationLkpIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DdpCommunicationLkpIntegrationTest: @Transactional;
    
    @Autowired
    DdpCommunicationLkpDataOnDemand DdpCommunicationLkpIntegrationTest.dod;
    
    @Autowired
    DdpCommunicationLkpService DdpCommunicationLkpIntegrationTest.ddpCommunicationLkpService;
    
    @Autowired
    DdpCommunicationLkpRepository DdpCommunicationLkpIntegrationTest.ddpCommunicationLkpRepository;
    
    @Test
    public void DdpCommunicationLkpIntegrationTest.testCountAllDdpCommunicationLkps() {
        Assert.assertNotNull("Data on demand for 'DdpCommunicationLkp' failed to initialize correctly", dod.getRandomDdpCommunicationLkp());
        long count = ddpCommunicationLkpService.countAllDdpCommunicationLkps();
        Assert.assertTrue("Counter for 'DdpCommunicationLkp' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DdpCommunicationLkpIntegrationTest.testFindDdpCommunicationLkp() {
        DdpCommunicationLkp obj = dod.getRandomDdpCommunicationLkp();
        Assert.assertNotNull("Data on demand for 'DdpCommunicationLkp' failed to initialize correctly", obj);
        Integer id = obj.getColCommunicationLkpId();
        Assert.assertNotNull("Data on demand for 'DdpCommunicationLkp' failed to provide an identifier", id);
        obj = ddpCommunicationLkpService.findDdpCommunicationLkp(id);
        Assert.assertNotNull("Find method for 'DdpCommunicationLkp' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DdpCommunicationLkp' returned the incorrect identifier", id, obj.getColCommunicationLkpId());
    }
    
    @Test
    public void DdpCommunicationLkpIntegrationTest.testFindAllDdpCommunicationLkps() {
        Assert.assertNotNull("Data on demand for 'DdpCommunicationLkp' failed to initialize correctly", dod.getRandomDdpCommunicationLkp());
        long count = ddpCommunicationLkpService.countAllDdpCommunicationLkps();
        Assert.assertTrue("Too expensive to perform a find all test for 'DdpCommunicationLkp', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DdpCommunicationLkp> result = ddpCommunicationLkpService.findAllDdpCommunicationLkps();
        Assert.assertNotNull("Find all method for 'DdpCommunicationLkp' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DdpCommunicationLkp' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DdpCommunicationLkpIntegrationTest.testFindDdpCommunicationLkpEntries() {
        Assert.assertNotNull("Data on demand for 'DdpCommunicationLkp' failed to initialize correctly", dod.getRandomDdpCommunicationLkp());
        long count = ddpCommunicationLkpService.countAllDdpCommunicationLkps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DdpCommunicationLkp> result = ddpCommunicationLkpService.findDdpCommunicationLkpEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DdpCommunicationLkp' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DdpCommunicationLkp' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DdpCommunicationLkpIntegrationTest.testSaveDdpCommunicationLkp() {
        Assert.assertNotNull("Data on demand for 'DdpCommunicationLkp' failed to initialize correctly", dod.getRandomDdpCommunicationLkp());
        DdpCommunicationLkp obj = dod.getNewTransientDdpCommunicationLkp(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DdpCommunicationLkp' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DdpCommunicationLkp' identifier to be null", obj.getColCommunicationLkpId());
        try {
            ddpCommunicationLkpService.saveDdpCommunicationLkp(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        ddpCommunicationLkpRepository.flush();
        Assert.assertNotNull("Expected 'DdpCommunicationLkp' identifier to no longer be null", obj.getColCommunicationLkpId());
    }
    
    @Test
    public void DdpCommunicationLkpIntegrationTest.testDeleteDdpCommunicationLkp() {
        DdpCommunicationLkp obj = dod.getRandomDdpCommunicationLkp();
        Assert.assertNotNull("Data on demand for 'DdpCommunicationLkp' failed to initialize correctly", obj);
        Integer id = obj.getColCommunicationLkpId();
        Assert.assertNotNull("Data on demand for 'DdpCommunicationLkp' failed to provide an identifier", id);
        obj = ddpCommunicationLkpService.findDdpCommunicationLkp(id);
        ddpCommunicationLkpService.deleteDdpCommunicationLkp(obj);
        ddpCommunicationLkpRepository.flush();
        Assert.assertNull("Failed to remove 'DdpCommunicationLkp' with identifier '" + id + "'", ddpCommunicationLkpService.findDdpCommunicationLkp(id));
    }
    
}
