// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpDmsDocsTxnDataOnDemand;
import com.agility.ddp.data.domain.DdpDmsDocsTxnIntegrationTest;
import com.agility.ddp.data.domain.DdpDmsDocsTxnRepository;
import com.agility.ddp.data.domain.DdpDmsDocsTxnService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DdpDmsDocsTxnIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DdpDmsDocsTxnIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DdpDmsDocsTxnIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DdpDmsDocsTxnIntegrationTest: @Transactional;
    
    @Autowired
    DdpDmsDocsTxnDataOnDemand DdpDmsDocsTxnIntegrationTest.dod;
    
    @Autowired
    DdpDmsDocsTxnService DdpDmsDocsTxnIntegrationTest.ddpDmsDocsTxnService;
    
    @Autowired
    DdpDmsDocsTxnRepository DdpDmsDocsTxnIntegrationTest.ddpDmsDocsTxnRepository;
    
    @Test
    public void DdpDmsDocsTxnIntegrationTest.testCountAllDdpDmsDocsTxns() {
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsTxn' failed to initialize correctly", dod.getRandomDdpDmsDocsTxn());
        long count = ddpDmsDocsTxnService.countAllDdpDmsDocsTxns();
        Assert.assertTrue("Counter for 'DdpDmsDocsTxn' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DdpDmsDocsTxnIntegrationTest.testFindDdpDmsDocsTxn() {
        DdpDmsDocsTxn obj = dod.getRandomDdpDmsDocsTxn();
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsTxn' failed to initialize correctly", obj);
        Integer id = obj.getDtxId();
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsTxn' failed to provide an identifier", id);
        obj = ddpDmsDocsTxnService.findDdpDmsDocsTxn(id);
        Assert.assertNotNull("Find method for 'DdpDmsDocsTxn' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DdpDmsDocsTxn' returned the incorrect identifier", id, obj.getDtxId());
    }
    
    @Test
    public void DdpDmsDocsTxnIntegrationTest.testFindAllDdpDmsDocsTxns() {
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsTxn' failed to initialize correctly", dod.getRandomDdpDmsDocsTxn());
        long count = ddpDmsDocsTxnService.countAllDdpDmsDocsTxns();
        Assert.assertTrue("Too expensive to perform a find all test for 'DdpDmsDocsTxn', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DdpDmsDocsTxn> result = ddpDmsDocsTxnService.findAllDdpDmsDocsTxns();
        Assert.assertNotNull("Find all method for 'DdpDmsDocsTxn' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DdpDmsDocsTxn' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DdpDmsDocsTxnIntegrationTest.testFindDdpDmsDocsTxnEntries() {
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsTxn' failed to initialize correctly", dod.getRandomDdpDmsDocsTxn());
        long count = ddpDmsDocsTxnService.countAllDdpDmsDocsTxns();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DdpDmsDocsTxn> result = ddpDmsDocsTxnService.findDdpDmsDocsTxnEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DdpDmsDocsTxn' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DdpDmsDocsTxn' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DdpDmsDocsTxnIntegrationTest.testSaveDdpDmsDocsTxn() {
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsTxn' failed to initialize correctly", dod.getRandomDdpDmsDocsTxn());
        DdpDmsDocsTxn obj = dod.getNewTransientDdpDmsDocsTxn(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsTxn' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DdpDmsDocsTxn' identifier to be null", obj.getDtxId());
        try {
            ddpDmsDocsTxnService.saveDdpDmsDocsTxn(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        ddpDmsDocsTxnRepository.flush();
        Assert.assertNotNull("Expected 'DdpDmsDocsTxn' identifier to no longer be null", obj.getDtxId());
    }
    
    @Test
    public void DdpDmsDocsTxnIntegrationTest.testDeleteDdpDmsDocsTxn() {
        DdpDmsDocsTxn obj = dod.getRandomDdpDmsDocsTxn();
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsTxn' failed to initialize correctly", obj);
        Integer id = obj.getDtxId();
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsTxn' failed to provide an identifier", id);
        obj = ddpDmsDocsTxnService.findDdpDmsDocsTxn(id);
        ddpDmsDocsTxnService.deleteDdpDmsDocsTxn(obj);
        ddpDmsDocsTxnRepository.flush();
        Assert.assertNull("Failed to remove 'DdpDmsDocsTxn' with identifier '" + id + "'", ddpDmsDocsTxnService.findDdpDmsDocsTxn(id));
    }
    
}
