// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpDmsDocsDetailDataOnDemand;
import com.agility.ddp.data.domain.DdpDmsDocsDetailIntegrationTest;
import com.agility.ddp.data.domain.DdpDmsDocsDetailRepository;
import com.agility.ddp.data.domain.DdpDmsDocsDetailService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DdpDmsDocsDetailIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DdpDmsDocsDetailIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DdpDmsDocsDetailIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DdpDmsDocsDetailIntegrationTest: @Transactional;
    
    @Autowired
    DdpDmsDocsDetailDataOnDemand DdpDmsDocsDetailIntegrationTest.dod;
    
    @Autowired
    DdpDmsDocsDetailService DdpDmsDocsDetailIntegrationTest.ddpDmsDocsDetailService;
    
    @Autowired
    DdpDmsDocsDetailRepository DdpDmsDocsDetailIntegrationTest.ddpDmsDocsDetailRepository;
    
    @Test
    public void DdpDmsDocsDetailIntegrationTest.testCountAllDdpDmsDocsDetails() {
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsDetail' failed to initialize correctly", dod.getRandomDdpDmsDocsDetail());
        long count = ddpDmsDocsDetailService.countAllDdpDmsDocsDetails();
        Assert.assertTrue("Counter for 'DdpDmsDocsDetail' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DdpDmsDocsDetailIntegrationTest.testFindDdpDmsDocsDetail() {
        DdpDmsDocsDetail obj = dod.getRandomDdpDmsDocsDetail();
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsDetail' failed to initialize correctly", obj);
        Integer id = obj.getDddId();
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsDetail' failed to provide an identifier", id);
        obj = ddpDmsDocsDetailService.findDdpDmsDocsDetail(id);
        Assert.assertNotNull("Find method for 'DdpDmsDocsDetail' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DdpDmsDocsDetail' returned the incorrect identifier", id, obj.getDddId());
    }
    
    @Test
    public void DdpDmsDocsDetailIntegrationTest.testFindAllDdpDmsDocsDetails() {
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsDetail' failed to initialize correctly", dod.getRandomDdpDmsDocsDetail());
        long count = ddpDmsDocsDetailService.countAllDdpDmsDocsDetails();
        Assert.assertTrue("Too expensive to perform a find all test for 'DdpDmsDocsDetail', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DdpDmsDocsDetail> result = ddpDmsDocsDetailService.findAllDdpDmsDocsDetails();
        Assert.assertNotNull("Find all method for 'DdpDmsDocsDetail' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DdpDmsDocsDetail' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DdpDmsDocsDetailIntegrationTest.testFindDdpDmsDocsDetailEntries() {
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsDetail' failed to initialize correctly", dod.getRandomDdpDmsDocsDetail());
        long count = ddpDmsDocsDetailService.countAllDdpDmsDocsDetails();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DdpDmsDocsDetail> result = ddpDmsDocsDetailService.findDdpDmsDocsDetailEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DdpDmsDocsDetail' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DdpDmsDocsDetail' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DdpDmsDocsDetailIntegrationTest.testSaveDdpDmsDocsDetail() {
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsDetail' failed to initialize correctly", dod.getRandomDdpDmsDocsDetail());
        DdpDmsDocsDetail obj = dod.getNewTransientDdpDmsDocsDetail(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsDetail' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DdpDmsDocsDetail' identifier to be null", obj.getDddId());
        try {
            ddpDmsDocsDetailService.saveDdpDmsDocsDetail(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        ddpDmsDocsDetailRepository.flush();
        Assert.assertNotNull("Expected 'DdpDmsDocsDetail' identifier to no longer be null", obj.getDddId());
    }
    
    @Test
    public void DdpDmsDocsDetailIntegrationTest.testDeleteDdpDmsDocsDetail() {
        DdpDmsDocsDetail obj = dod.getRandomDdpDmsDocsDetail();
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsDetail' failed to initialize correctly", obj);
        Integer id = obj.getDddId();
        Assert.assertNotNull("Data on demand for 'DdpDmsDocsDetail' failed to provide an identifier", id);
        obj = ddpDmsDocsDetailService.findDdpDmsDocsDetail(id);
        ddpDmsDocsDetailService.deleteDdpDmsDocsDetail(obj);
        ddpDmsDocsDetailRepository.flush();
        Assert.assertNull("Failed to remove 'DdpDmsDocsDetail' with identifier '" + id + "'", ddpDmsDocsDetailService.findDdpDmsDocsDetail(id));
    }
    
}
