// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpExportRuleDataOnDemand;
import com.agility.ddp.data.domain.DdpExportRuleIntegrationTest;
import com.agility.ddp.data.domain.DdpExportRuleRepository;
import com.agility.ddp.data.domain.DdpExportRuleService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DdpExportRuleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DdpExportRuleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DdpExportRuleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DdpExportRuleIntegrationTest: @Transactional;
    
    @Autowired
    DdpExportRuleDataOnDemand DdpExportRuleIntegrationTest.dod;
    
    @Autowired
    DdpExportRuleService DdpExportRuleIntegrationTest.ddpExportRuleService;
    
    @Autowired
    DdpExportRuleRepository DdpExportRuleIntegrationTest.ddpExportRuleRepository;
    
    @Test
    public void DdpExportRuleIntegrationTest.testCountAllDdpExportRules() {
        Assert.assertNotNull("Data on demand for 'DdpExportRule' failed to initialize correctly", dod.getRandomDdpExportRule());
        long count = ddpExportRuleService.countAllDdpExportRules();
        Assert.assertTrue("Counter for 'DdpExportRule' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DdpExportRuleIntegrationTest.testFindDdpExportRule() {
        DdpExportRule obj = dod.getRandomDdpExportRule();
        Assert.assertNotNull("Data on demand for 'DdpExportRule' failed to initialize correctly", obj);
        Integer id = obj.getExpRuleId();
        Assert.assertNotNull("Data on demand for 'DdpExportRule' failed to provide an identifier", id);
        obj = ddpExportRuleService.findDdpExportRule(id);
        Assert.assertNotNull("Find method for 'DdpExportRule' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DdpExportRule' returned the incorrect identifier", id, obj.getExpRuleId());
    }
    
    @Test
    public void DdpExportRuleIntegrationTest.testFindAllDdpExportRules() {
        Assert.assertNotNull("Data on demand for 'DdpExportRule' failed to initialize correctly", dod.getRandomDdpExportRule());
        long count = ddpExportRuleService.countAllDdpExportRules();
        Assert.assertTrue("Too expensive to perform a find all test for 'DdpExportRule', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DdpExportRule> result = ddpExportRuleService.findAllDdpExportRules();
        Assert.assertNotNull("Find all method for 'DdpExportRule' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DdpExportRule' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DdpExportRuleIntegrationTest.testFindDdpExportRuleEntries() {
        Assert.assertNotNull("Data on demand for 'DdpExportRule' failed to initialize correctly", dod.getRandomDdpExportRule());
        long count = ddpExportRuleService.countAllDdpExportRules();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DdpExportRule> result = ddpExportRuleService.findDdpExportRuleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DdpExportRule' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DdpExportRule' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DdpExportRuleIntegrationTest.testSaveDdpExportRule() {
        Assert.assertNotNull("Data on demand for 'DdpExportRule' failed to initialize correctly", dod.getRandomDdpExportRule());
        DdpExportRule obj = dod.getNewTransientDdpExportRule(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DdpExportRule' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DdpExportRule' identifier to be null", obj.getExpRuleId());
        try {
            ddpExportRuleService.saveDdpExportRule(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        ddpExportRuleRepository.flush();
        Assert.assertNotNull("Expected 'DdpExportRule' identifier to no longer be null", obj.getExpRuleId());
    }
    
    @Test
    public void DdpExportRuleIntegrationTest.testDeleteDdpExportRule() {
        DdpExportRule obj = dod.getRandomDdpExportRule();
        Assert.assertNotNull("Data on demand for 'DdpExportRule' failed to initialize correctly", obj);
        Integer id = obj.getExpRuleId();
        Assert.assertNotNull("Data on demand for 'DdpExportRule' failed to provide an identifier", id);
        obj = ddpExportRuleService.findDdpExportRule(id);
        ddpExportRuleService.deleteDdpExportRule(obj);
        ddpExportRuleRepository.flush();
        Assert.assertNull("Failed to remove 'DdpExportRule' with identifier '" + id + "'", ddpExportRuleService.findDdpExportRule(id));
    }
    
}
