// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpExportVersionLkpDataOnDemand;
import com.agility.ddp.data.domain.DdpExportVersionLkpIntegrationTest;
import com.agility.ddp.data.domain.DdpExportVersionLkpPK;
import com.agility.ddp.data.domain.DdpExportVersionLkpRepository;
import com.agility.ddp.data.domain.DdpExportVersionLkpService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DdpExportVersionLkpIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DdpExportVersionLkpIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DdpExportVersionLkpIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DdpExportVersionLkpIntegrationTest: @Transactional;
    
    @Autowired
    DdpExportVersionLkpDataOnDemand DdpExportVersionLkpIntegrationTest.dod;
    
    @Autowired
    DdpExportVersionLkpService DdpExportVersionLkpIntegrationTest.ddpExportVersionLkpService;
    
    @Autowired
    DdpExportVersionLkpRepository DdpExportVersionLkpIntegrationTest.ddpExportVersionLkpRepository;
    
    @Test
    public void DdpExportVersionLkpIntegrationTest.testCountAllDdpExportVersionLkps() {
        Assert.assertNotNull("Data on demand for 'DdpExportVersionLkp' failed to initialize correctly", dod.getRandomDdpExportVersionLkp());
        long count = ddpExportVersionLkpService.countAllDdpExportVersionLkps();
        Assert.assertTrue("Counter for 'DdpExportVersionLkp' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DdpExportVersionLkpIntegrationTest.testFindDdpExportVersionLkp() {
        DdpExportVersionLkp obj = dod.getRandomDdpExportVersionLkp();
        Assert.assertNotNull("Data on demand for 'DdpExportVersionLkp' failed to initialize correctly", obj);
        DdpExportVersionLkpPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DdpExportVersionLkp' failed to provide an identifier", id);
        obj = ddpExportVersionLkpService.findDdpExportVersionLkp(id);
        Assert.assertNotNull("Find method for 'DdpExportVersionLkp' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DdpExportVersionLkp' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DdpExportVersionLkpIntegrationTest.testFindAllDdpExportVersionLkps() {
        Assert.assertNotNull("Data on demand for 'DdpExportVersionLkp' failed to initialize correctly", dod.getRandomDdpExportVersionLkp());
        long count = ddpExportVersionLkpService.countAllDdpExportVersionLkps();
        Assert.assertTrue("Too expensive to perform a find all test for 'DdpExportVersionLkp', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DdpExportVersionLkp> result = ddpExportVersionLkpService.findAllDdpExportVersionLkps();
        Assert.assertNotNull("Find all method for 'DdpExportVersionLkp' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DdpExportVersionLkp' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DdpExportVersionLkpIntegrationTest.testFindDdpExportVersionLkpEntries() {
        Assert.assertNotNull("Data on demand for 'DdpExportVersionLkp' failed to initialize correctly", dod.getRandomDdpExportVersionLkp());
        long count = ddpExportVersionLkpService.countAllDdpExportVersionLkps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DdpExportVersionLkp> result = ddpExportVersionLkpService.findDdpExportVersionLkpEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DdpExportVersionLkp' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DdpExportVersionLkp' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DdpExportVersionLkpIntegrationTest.testSaveDdpExportVersionLkp() {
        Assert.assertNotNull("Data on demand for 'DdpExportVersionLkp' failed to initialize correctly", dod.getRandomDdpExportVersionLkp());
        DdpExportVersionLkp obj = dod.getNewTransientDdpExportVersionLkp(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DdpExportVersionLkp' failed to provide a new transient entity", obj);
        try {
            ddpExportVersionLkpService.saveDdpExportVersionLkp(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        ddpExportVersionLkpRepository.flush();
        Assert.assertNotNull("Expected 'DdpExportVersionLkp' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DdpExportVersionLkpIntegrationTest.testDeleteDdpExportVersionLkp() {
        DdpExportVersionLkp obj = dod.getRandomDdpExportVersionLkp();
        Assert.assertNotNull("Data on demand for 'DdpExportVersionLkp' failed to initialize correctly", obj);
        DdpExportVersionLkpPK id = obj.getId();
        Assert.assertNotNull("Data on demand for 'DdpExportVersionLkp' failed to provide an identifier", id);
        obj = ddpExportVersionLkpService.findDdpExportVersionLkp(id);
        ddpExportVersionLkpService.deleteDdpExportVersionLkp(obj);
        ddpExportVersionLkpRepository.flush();
        Assert.assertNull("Failed to remove 'DdpExportVersionLkp' with identifier '" + id + "'", ddpExportVersionLkpService.findDdpExportVersionLkp(id));
    }
    
}
