// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpGenSourceLkpIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DdpGenSourceLkpIntegrationTest_Roo_Configurable {
    
    declare @type: DdpGenSourceLkpIntegrationTest: @Configurable;
    
}
