// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpMultiAedRuleDataOnDemand;
import com.agility.ddp.data.domain.DdpMultiAedRuleIntegrationTest;
import com.agility.ddp.data.domain.DdpMultiAedRuleRepository;
import com.agility.ddp.data.domain.DdpMultiAedRuleService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DdpMultiAedRuleIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DdpMultiAedRuleIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DdpMultiAedRuleIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DdpMultiAedRuleIntegrationTest: @Transactional;
    
    @Autowired
    DdpMultiAedRuleDataOnDemand DdpMultiAedRuleIntegrationTest.dod;
    
    @Autowired
    DdpMultiAedRuleService DdpMultiAedRuleIntegrationTest.ddpMultiAedRuleService;
    
    @Autowired
    DdpMultiAedRuleRepository DdpMultiAedRuleIntegrationTest.ddpMultiAedRuleRepository;
    
    @Test
    public void DdpMultiAedRuleIntegrationTest.testCountAllDdpMultiAedRules() {
        Assert.assertNotNull("Data on demand for 'DdpMultiAedRule' failed to initialize correctly", dod.getRandomDdpMultiAedRule());
        long count = ddpMultiAedRuleService.countAllDdpMultiAedRules();
        Assert.assertTrue("Counter for 'DdpMultiAedRule' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DdpMultiAedRuleIntegrationTest.testFindDdpMultiAedRule() {
        DdpMultiAedRule obj = dod.getRandomDdpMultiAedRule();
        Assert.assertNotNull("Data on demand for 'DdpMultiAedRule' failed to initialize correctly", obj);
        Integer id = obj.getMaedRuleId();
        Assert.assertNotNull("Data on demand for 'DdpMultiAedRule' failed to provide an identifier", id);
        obj = ddpMultiAedRuleService.findDdpMultiAedRule(id);
        Assert.assertNotNull("Find method for 'DdpMultiAedRule' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DdpMultiAedRule' returned the incorrect identifier", id, obj.getMaedRuleId());
    }
    
    @Test
    public void DdpMultiAedRuleIntegrationTest.testFindAllDdpMultiAedRules() {
        Assert.assertNotNull("Data on demand for 'DdpMultiAedRule' failed to initialize correctly", dod.getRandomDdpMultiAedRule());
        long count = ddpMultiAedRuleService.countAllDdpMultiAedRules();
        Assert.assertTrue("Too expensive to perform a find all test for 'DdpMultiAedRule', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DdpMultiAedRule> result = ddpMultiAedRuleService.findAllDdpMultiAedRules();
        Assert.assertNotNull("Find all method for 'DdpMultiAedRule' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DdpMultiAedRule' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DdpMultiAedRuleIntegrationTest.testFindDdpMultiAedRuleEntries() {
        Assert.assertNotNull("Data on demand for 'DdpMultiAedRule' failed to initialize correctly", dod.getRandomDdpMultiAedRule());
        long count = ddpMultiAedRuleService.countAllDdpMultiAedRules();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DdpMultiAedRule> result = ddpMultiAedRuleService.findDdpMultiAedRuleEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DdpMultiAedRule' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DdpMultiAedRule' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DdpMultiAedRuleIntegrationTest.testSaveDdpMultiAedRule() {
        Assert.assertNotNull("Data on demand for 'DdpMultiAedRule' failed to initialize correctly", dod.getRandomDdpMultiAedRule());
        DdpMultiAedRule obj = dod.getNewTransientDdpMultiAedRule(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DdpMultiAedRule' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DdpMultiAedRule' identifier to be null", obj.getMaedRuleId());
        try {
            ddpMultiAedRuleService.saveDdpMultiAedRule(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        ddpMultiAedRuleRepository.flush();
        Assert.assertNotNull("Expected 'DdpMultiAedRule' identifier to no longer be null", obj.getMaedRuleId());
    }
    
    @Test
    public void DdpMultiAedRuleIntegrationTest.testDeleteDdpMultiAedRule() {
        DdpMultiAedRule obj = dod.getRandomDdpMultiAedRule();
        Assert.assertNotNull("Data on demand for 'DdpMultiAedRule' failed to initialize correctly", obj);
        Integer id = obj.getMaedRuleId();
        Assert.assertNotNull("Data on demand for 'DdpMultiAedRule' failed to provide an identifier", id);
        obj = ddpMultiAedRuleService.findDdpMultiAedRule(id);
        ddpMultiAedRuleService.deleteDdpMultiAedRule(obj);
        ddpMultiAedRuleRepository.flush();
        Assert.assertNull("Failed to remove 'DdpMultiAedRule' with identifier '" + id + "'", ddpMultiAedRuleService.findDdpMultiAedRule(id));
    }
    
}
