// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpRateLkpDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect DdpRateLkpDataOnDemand_Roo_Configurable {
    
    declare @type: DdpRateLkpDataOnDemand: @Configurable;
    
}
