// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.agility.ddp.data.domain;

import com.agility.ddp.data.domain.DdpValueAsstDataOnDemand;
import com.agility.ddp.data.domain.DdpValueAsstIntegrationTest;
import com.agility.ddp.data.domain.DdpValueAsstRepository;
import com.agility.ddp.data.domain.DdpValueAsstService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DdpValueAsstIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DdpValueAsstIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DdpValueAsstIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DdpValueAsstIntegrationTest: @Transactional;
    
    @Autowired
    DdpValueAsstDataOnDemand DdpValueAsstIntegrationTest.dod;
    
    @Autowired
    DdpValueAsstService DdpValueAsstIntegrationTest.ddpValueAsstService;
    
    @Autowired
    DdpValueAsstRepository DdpValueAsstIntegrationTest.ddpValueAsstRepository;
    
    @Test
    public void DdpValueAsstIntegrationTest.testCountAllDdpValueAssts() {
        Assert.assertNotNull("Data on demand for 'DdpValueAsst' failed to initialize correctly", dod.getRandomDdpValueAsst());
        long count = ddpValueAsstService.countAllDdpValueAssts();
        Assert.assertTrue("Counter for 'DdpValueAsst' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DdpValueAsstIntegrationTest.testFindDdpValueAsst() {
        DdpValueAsst obj = dod.getRandomDdpValueAsst();
        Assert.assertNotNull("Data on demand for 'DdpValueAsst' failed to initialize correctly", obj);
        Integer id = obj.getVlaId();
        Assert.assertNotNull("Data on demand for 'DdpValueAsst' failed to provide an identifier", id);
        obj = ddpValueAsstService.findDdpValueAsst(id);
        Assert.assertNotNull("Find method for 'DdpValueAsst' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'DdpValueAsst' returned the incorrect identifier", id, obj.getVlaId());
    }
    
    @Test
    public void DdpValueAsstIntegrationTest.testFindAllDdpValueAssts() {
        Assert.assertNotNull("Data on demand for 'DdpValueAsst' failed to initialize correctly", dod.getRandomDdpValueAsst());
        long count = ddpValueAsstService.countAllDdpValueAssts();
        Assert.assertTrue("Too expensive to perform a find all test for 'DdpValueAsst', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<DdpValueAsst> result = ddpValueAsstService.findAllDdpValueAssts();
        Assert.assertNotNull("Find all method for 'DdpValueAsst' illegally returned null", result);
        Assert.assertTrue("Find all method for 'DdpValueAsst' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DdpValueAsstIntegrationTest.testFindDdpValueAsstEntries() {
        Assert.assertNotNull("Data on demand for 'DdpValueAsst' failed to initialize correctly", dod.getRandomDdpValueAsst());
        long count = ddpValueAsstService.countAllDdpValueAssts();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<DdpValueAsst> result = ddpValueAsstService.findDdpValueAsstEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'DdpValueAsst' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'DdpValueAsst' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DdpValueAsstIntegrationTest.testSaveDdpValueAsst() {
        Assert.assertNotNull("Data on demand for 'DdpValueAsst' failed to initialize correctly", dod.getRandomDdpValueAsst());
        DdpValueAsst obj = dod.getNewTransientDdpValueAsst(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'DdpValueAsst' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'DdpValueAsst' identifier to be null", obj.getVlaId());
        try {
            ddpValueAsstService.saveDdpValueAsst(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        ddpValueAsstRepository.flush();
        Assert.assertNotNull("Expected 'DdpValueAsst' identifier to no longer be null", obj.getVlaId());
    }
    
    @Test
    public void DdpValueAsstIntegrationTest.testDeleteDdpValueAsst() {
        DdpValueAsst obj = dod.getRandomDdpValueAsst();
        Assert.assertNotNull("Data on demand for 'DdpValueAsst' failed to initialize correctly", obj);
        Integer id = obj.getVlaId();
        Assert.assertNotNull("Data on demand for 'DdpValueAsst' failed to provide an identifier", id);
        obj = ddpValueAsstService.findDdpValueAsst(id);
        ddpValueAsstService.deleteDdpValueAsst(obj);
        ddpValueAsstRepository.flush();
        Assert.assertNull("Failed to remove 'DdpValueAsst' with identifier '" + id + "'", ddpValueAsstService.findDdpValueAsst(id));
    }
    
}
